import { Header } from "@/components/layout/header";

export const metadata = {
  title: "Terms of Service - FORM",
  description: "Terms of Service for FORM Website-to-product studio",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-canvas">
      <Header />
      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-display font-semibold text-ink mb-8">Terms of Service</h1>
        <div className="prose prose-ink max-w-none">
          <p className="text-text-secondary mb-6">Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Acceptance of Terms</h2>
          <p className="text-text-secondary mb-4">By accessing or using FORM, you agree to be bound by these Terms of Service and our Privacy Policy.</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Use of the Service</h2>
          <p className="text-text-secondary mb-4">FORM is a website-to-product studio that analyzes websites and generates product concepts. You agree to use the service only for lawful purposes and in accordance with these Terms.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Accounts</h2>
          <p className="text-text-secondary mb-4">You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Intellectual Property</h2>
          <p className="text-text-secondary mb-4">The service and its original content, features, and functionality are owned by FORM and are protected by international copyright, trademark, and other intellectual property laws.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Generated Content</h2>
          <p className="text-text-secondary mb-4">Product concepts, designs, and code generated by FORM are provided as starting points. You are responsible for reviewing and modifying generated content before use.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Disclaimer of Warranties</h2>
           <p className="text-text-secondary mb-4">The service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Limitation of Liability</h2>
          <p className="text-text-secondary mb-4">In no event shall FORM be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Termination</h2>
          <p className="text-text-secondary mb-4">We may terminate or suspend your account and access to the service immediately, without prior notice, for conduct that we believe violates these Terms.
</p>
          
          <h2 className="text-2xl font-semibold text-ink mt-10 mb-4">Contact Us</h2>
          <p className="text-text-secondary mb-4">If you have any questions about these Terms, please contact us at legal@form.example.com.</p>
        </div>
      </main>
    </div>
  );
}
