"use client";

import { X } from "lucide-react";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetTitle } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { formatStatusLabel } from "@/components/dashboard/status-label";
import { VersionHistory } from "@/components/dashboard/version-history";

type Run = { id: string; kind: string; status: string; stage: string | null; created_at?: string; started_at?: string | null; finished_at?: string | null; error_message?: string | null; steps: { stage_key: string; status: string; started_at?: string | null; finished_at?: string | null; error_code?: string | null }[] };
type SheetData = { recentJobs: Run[]; captures: { requested_url: string; title?: string | null; screenshot_path?: string | null; captured_at: string }[]; analysis: { summary_claim?: string; analysis_evidence?: { source_url?: string; excerpt?: string }[]; analysis_visual?: { layout?: string; palette?: string; hierarchy?: string; density?: string }[] } | null; qaReports: { status: string; checks: unknown[]; ai_findings: unknown[] }[]; exports: { id: string; status: string; storage_path: string }[] };

export function ProjectRunSheet({ open, onOpenChange, data, projectId, currentVersionId, onRestored, selectedJobId, onSelectJob, onRunQa, qaStarting, hasActiveJob }: { open: boolean; onOpenChange: (open: boolean) => void; data: SheetData; projectId: string; currentVersionId: string | null; onRestored: () => void; selectedJobId: string | null; onSelectJob: (id: string) => void; onRunQa: () => void; qaStarting: boolean; hasActiveJob: boolean }) {
  const selected = data.recentJobs.find((job) => job.id === selectedJobId) || data.recentJobs[0];
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent side="right"><div className="flex items-start justify-between border-b border-line px-6 py-5"><div><SheetTitle>Runs and details</SheetTitle><SheetDescription>Live operational context for this product.</SheetDescription></div><SheetClose asChild><button type="button" aria-label="Close runs and details" className="rounded-control p-2 text-text-secondary hover:bg-surface-muted"><X className="h-4 w-4" /></button></SheetClose></div><div className="space-y-7 p-6">
       <section><div className="mb-3 flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[0.14em] text-text-secondary">Recent runs</p><Button size="sm" variant="outline" onClick={onRunQa} disabled={qaStarting || hasActiveJob}>{qaStarting ? "Starting QA..." : hasActiveJob ? "Run in progress" : "Run QA"}</Button></div><p className="mb-3 text-xs text-text-secondary">Checks the current version&apos;s preview and records findings here. New operations unlock when the active run finishes.</p><div className="space-y-2">{data.recentJobs.length === 0 && <p className="rounded-control border border-dashed border-line p-3 text-xs text-text-secondary">No runs yet.</p>}{data.recentJobs.map((job) => <button key={job.id} type="button" onClick={() => onSelectJob(job.id)} className={`w-full rounded-control border p-3 text-left ${selected?.id === job.id ? "border-accent bg-accent/10" : "border-line hover:bg-surface-muted"}`}><div className="flex items-center justify-between gap-3"><span className="font-semibold capitalize text-text">{formatStatusLabel(job.kind)}</span><span className="text-xs text-text-secondary">{formatStatusLabel(job.status)}</span></div><p className="mt-1 text-xs text-text-secondary">{formatStatusLabel(job.stage || "queued")}{job.started_at ? ` · ${new Date(job.started_at).toLocaleTimeString()}` : ""}</p></button>)}</div></section>
    {selected && <section><p className="mb-3 text-xs font-bold uppercase tracking-[0.14em] text-text-secondary">Selected run</p><div className="rounded-panel border border-line p-4"><div className="flex items-center justify-between"><span className="font-semibold capitalize text-text">{formatStatusLabel(selected.kind)}</span><span className="rounded-chip bg-surface-muted px-2 py-1 text-xs text-text-secondary">{formatStatusLabel(selected.status)}</span></div><div className="mt-4 space-y-3">{(selected.steps.length ? selected.steps : [{ stage_key: selected.stage || selected.kind, status: selected.status }]).map((step) => <div key={step.stage_key} className="flex items-center justify-between gap-3 text-sm"><span className="text-text-secondary">{formatStatusLabel(step.stage_key)}</span><span className={step.status === "succeeded" ? "text-success" : step.status === "failed" ? "text-danger" : "text-text"}>{formatStatusLabel(step.status)}</span></div>)}</div>{selected.error_message && <p className="mt-4 rounded-control bg-danger/10 p-3 text-sm text-danger">{selected.error_message}</p>}</div></section>}
    {data.captures[0] && <section><p className="mb-3 text-xs font-bold uppercase tracking-[0.14em] text-text-secondary">Source capture</p><div className="space-y-3 rounded-panel border border-line p-4"><p className="font-medium text-text">{data.captures[0].title || "Captured source"}</p><p className="truncate text-xs text-text-secondary">{data.captures[0].requested_url}</p>{data.captures[0].screenshot_path && <div className="relative h-64 w-full overflow-hidden rounded-control border border-line"><Image src={data.captures[0].screenshot_path} alt={`Screenshot of ${data.captures[0].title || "captured source website"}`} fill sizes="(max-width: 640px) 100vw, 384px" unoptimized className="object-cover object-top" /></div>}<p className="text-xs text-text-secondary">Captured {new Date(data.captures[0].captured_at).toLocaleString()}</p></div></section>}
      {data.analysis && <section><p className="mb-3 text-xs font-bold uppercase tracking-[0.14em] text-text-secondary">Visual system and evidence</p><div className="space-y-3 rounded-panel border border-line p-4"><p className="text-sm text-text-secondary">{data.analysis.summary_claim}</p>{data.analysis.analysis_visual?.[0] && <div className="grid grid-cols-2 gap-2 text-xs text-text-secondary"><span>Layout: {data.analysis.analysis_visual[0].layout || "Not captured"}</span><span>Palette: {data.analysis.analysis_visual[0].palette || "Not captured"}</span><span>Hierarchy: {data.analysis.analysis_visual[0].hierarchy || "Not captured"}</span><span>Density: {data.analysis.analysis_visual[0].density || "Not captured"}</span></div>}{data.analysis.analysis_evidence?.slice(0, 5).map((item, index) => <blockquote key={index} className="border-l-2 border-accent pl-3 text-xs text-text-secondary">“{item.excerpt}”</blockquote>)}</div></section>}
        <section><p className="mb-3 text-xs font-bold uppercase tracking-[0.14em] text-text-secondary">Version history</p><VersionHistory projectId={projectId} currentVersionId={currentVersionId} onRestored={onRestored} /></section>
        <section><p className="mb-3 text-xs font-bold uppercase tracking-[0.14em] text-text-secondary">Exports</p>{data.exports[0] ? <div className="rounded-panel border border-line p-4 text-sm"><div className="flex justify-between gap-3"><span className="font-semibold text-text">Latest export</span><span className="rounded-chip bg-surface-muted px-2 py-1 text-xs text-text-secondary">{formatStatusLabel(data.exports[0].status)}</span></div>{data.exports[0].status === "completed" ? <a href={`/api/exports/${data.exports[0].id}/download`} className="mt-3 inline-flex text-sm font-semibold text-text underline">Download export</a> : data.exports[0].status === "failed" ? <p className="mt-2 text-xs text-danger">Export failed. Check the latest run for details.</p> : <p className="mt-2 text-xs text-text-secondary">Export is being prepared. The download will be available when it completes.</p>}</div> : <p className="rounded-control border border-dashed border-line p-3 text-xs text-text-secondary">No export yet.</p>}</section>
  </div></SheetContent></Sheet>;
}
